### ISSUE TITLE
Headerbar too dark / too bright

### ISSUE THREAD

**Issue by ghost** [pojntfx/gtk-adwaita-ubuntu#1]
The headerbar is too dark (on my display pure black) in the dark version and too white (pure white on my display) on the white version.
It should be a little bit darker than the overall-color.

**Comment by pojntfx** [comment]
Sure! I was picking the color from the Unity8 screenshot's titlebar which was actually #000/#fff - should we stick to the truly dark/white Unity8 defaults or change it? Another option would be to make the titlebar buttons just Icons like in Communitheme and fix the weird look in this way. What do you think?
A video showing the colors: https://m.youtube.com/watch?v=B0SFVB05L1s
I've used #000 for the headerbar and a lighter shade (the unity8 dark theme "app body") for the rest

**Comment by ghost** [comment]
Hm... I think changing the buttons to icons like the Communitheme could make new problems. Maybe it would really be better to make the dark headerbar just a little bit brighter and the white headerbar just a little bit darker. Or is a shade-effect possible?

**Comment by pojntfx** [comment]
Shade would possible on the white but not on the dark version (A negative/light shadow would have to be used).
I guess I'm gonna use the active toggle color from https://raw.githubusercontent.com/pojntfx/gtk-adwaita-ubuntu/master/screenshots/settings-dark-lightblue.png to stay close to stock Adwaita. This should fix the weird look.

**Comment by pojntfx** [comment]
Adwaita-Dark defaults are now being used. Thanks for the feedback!
